const products = [
  {
    _id: '1',
    name: 'Oatmeal and banana',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 750,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Real beetroot and raisins',
    image: '/images/pound-cake/beetroot.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 750,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Jaggery and coconut',
    image: '/images/pound-cake/jaggery.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 750,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Almond Carrot flaxseed',
    image: '/images/pound-cake/almondcarrot.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 800,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Blueberry oatmeal pound cake',
    image: '/images/pound-cake/blueberry.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 800,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Whey protien dark chocolate',
    image: '/images/pound-cake/protien.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 850,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]


const cookie_product = [
  {
    _id: '7',
    name: 'Oatmeal and flaxseed',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 480,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Multigrain high fibre',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 510,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '9',
    name: 'Super seed quinoa',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 550,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Whey protien dark Choco chips',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 680,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Almond butter',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 850,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '12',
    name: 'Low karbs keto',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 1600,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

const muffin_product = [
  {
    _id: '13',
    name: 'Sugar free vanilla',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 239,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Blueberry oatmeal',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 289,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '15',
    name: 'Super seeds multigrain fibre',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 289,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '16',
    name: 'Almond raisins flaxseeds',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 329,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '17',
    name: 'Dark chocolate whey protien',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 369,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '18',
    name: 'Low carbs almond keto',
    image: '/images/pound-cake/oatmeal.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 510,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
const special_product = [
  {
    _id: '19',
    name: 'Whey protien chocolate brownie',
    image: '/images/special-treats/protienbrownie.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 999,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '20',
    name: 'Almond walnut Chocolate brownie',
    image: '/images/special-treats/browniealmond.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 899,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '21',
    name: 'Whey protien super bars',
    image: '/images/special-treats/protienbar.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 65,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '22',
    name: 'Chocolate almond keto bars',
    image: '/images/special-treats/ketobar.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 130,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
]
export default products
export {cookie_product,muffin_product,special_product}
